@startuml
class Eye {
    + cx : int
    + cy : int
    + r : int
    + fill : string
    + stroke : string
    + strokeWidth : string
    + Eye(cx:int, cy:int, r:int, fill:string, stroke:string, strokeWidth:string)
    + printShape(caretaker:Caretaker) : void
}
@enduml
