@startuml
class Mouth {
    + x1 : int
    + y1 : int
    + x2 : int
    + y2 : int
    + stroke : string
    + strokeWidth : string
    + Mouth(x1:int, y1:int, x2:int, y2:int, stroke:string, strokeWidth:string)
    + printShape(caretaker:Caretaker) : void
}
@enduml
