@startuml
class Polyline {
    + coords : string
    + fill : string
    + stroke : string
    + strokeWidth : string
    + Polyline(coords:string, fill:string, stroke:string, strokeWidth:string)
    + printShape() : string
}
@enduml
