@startuml
class Polygon {
    + coords : string
    + fill : string
    + stroke : string
    + strokeWidth : string
    + Polygon(coords:string, fill:string, stroke:string, strokeWidth:string)
    + printShape(caretaker:Caretaker) : void
}
@enduml
