@startuml
!include .\\CS264\Assignment1\Program.puml
!include .\\CS264\Assignment1\Tabconv.puml
!include .\\CS264\Assignment2\circ.puml
!include .\\CS264\Assignment2\createSVG.puml
!include .\\CS264\Assignment2\elli.puml
!include .\\CS264\Assignment2\line.puml
!include .\\CS264\Assignment2\path.puml
!include .\\CS264\Assignment2\pline.puml
!include .\\CS264\Assignment2\poly.puml
!include .\\CS264\Assignment2\Program.puml
!include .\\CS264\Assignment2\rect.puml
!include .\\CS264\Assignment3\caretaker.puml
!include .\\CS264\Assignment3\circ.puml
!include .\\CS264\Assignment3\elli.puml
!include .\\CS264\Assignment3\line.puml
!include .\\CS264\Assignment3\memento.puml
!include .\\CS264\Assignment3\path.puml
!include .\\CS264\Assignment3\pline.puml
!include .\\CS264\Assignment3\poly.puml
!include .\\CS264\Assignment3\Program.puml
!include .\\CS264\Assignment3\rect.puml
!include .\\CS264\Assignment4\circ.puml
!include .\\CS264\Assignment4\commandInt.puml
!include .\\CS264\Assignment4\elli.puml
!include .\\CS264\Assignment4\line.puml
!include .\\CS264\Assignment4\path.puml
!include .\\CS264\Assignment4\pline.puml
!include .\\CS264\Assignment4\poly.puml
!include .\\CS264\Assignment4\Program.puml
!include .\\CS264\Assignment4\rect.puml
!include .\\CS264\Assignment5\Assignment5_2\circ.puml
!include .\\CS264\Assignment5\Assignment5_2\createSVG.puml
!include .\\CS264\Assignment5\Assignment5_2\elli.puml
!include .\\CS264\Assignment5\Assignment5_2\factory.puml
!include .\\CS264\Assignment5\Assignment5_2\line.puml
!include .\\CS264\Assignment5\Assignment5_2\path.puml
!include .\\CS264\Assignment5\Assignment5_2\pline.puml
!include .\\CS264\Assignment5\Assignment5_2\poly.puml
!include .\\CS264\Assignment5\Assignment5_2\Program.puml
!include .\\CS264\Assignment5\Assignment5_2\rect.puml
!include .\\CS264\Assignment5\Assignment5_3\caretaker.puml
!include .\\CS264\Assignment5\Assignment5_3\circ.puml
!include .\\CS264\Assignment5\Assignment5_3\elli.puml
!include .\\CS264\Assignment5\Assignment5_3\factory.puml
!include .\\CS264\Assignment5\Assignment5_3\line.puml
!include .\\CS264\Assignment5\Assignment5_3\memento.puml
!include .\\CS264\Assignment5\Assignment5_3\path.puml
!include .\\CS264\Assignment5\Assignment5_3\pline.puml
!include .\\CS264\Assignment5\Assignment5_3\poly.puml
!include .\\CS264\Assignment5\Assignment5_3\Program.puml
!include .\\CS264\Assignment5\Assignment5_3\rect.puml
!include .\\CS264\Assignment5\Assignment5_4\circ.puml
!include .\\CS264\Assignment5\Assignment5_4\commandInt.puml
!include .\\CS264\Assignment5\Assignment5_4\elli.puml
!include .\\CS264\Assignment5\Assignment5_4\factory.puml
!include .\\CS264\Assignment5\Assignment5_4\line.puml
!include .\\CS264\Assignment5\Assignment5_4\path.puml
!include .\\CS264\Assignment5\Assignment5_4\pline.puml
!include .\\CS264\Assignment5\Assignment5_4\poly.puml
!include .\\CS264\Assignment5\Assignment5_4\Program.puml
!include .\\CS264\Assignment5\Assignment5_4\rect.puml
!include .\\CS264\Coding Assignment\Command\brow.puml
!include .\\CS264\Coding Assignment\Command\commandInt.puml
!include .\\CS264\Coding Assignment\Command\eye.puml
!include .\\CS264\Coding Assignment\Command\mouth.puml
!include .\\CS264\Coding Assignment\Command\Program.puml
!include .\\CS264\Coding Assignment\Memento\brow.puml
!include .\\CS264\Coding Assignment\Memento\caretaker.puml
!include .\\CS264\Coding Assignment\Memento\eye.puml
!include .\\CS264\Coding Assignment\Memento\memento.puml
!include .\\CS264\Coding Assignment\Memento\mouth.puml
!include .\\CS264\Coding Assignment\Memento\Program.puml
!include .\\CS264\Assignment1\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\CS264\Assignment1\obj\Debug\net6.0\Assignment1.AssemblyInfo.puml
!include .\\CS264\Assignment1\obj\Debug\net6.0\Assignment1.GlobalUsings.g.puml
!include .\\CS264\Assignment2\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\CS264\Assignment2\obj\Debug\net6.0\Assignment2.AssemblyInfo.puml
!include .\\CS264\Assignment2\obj\Debug\net6.0\Assignment2.GlobalUsings.g.puml
!include .\\CS264\Assignment3\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\CS264\Assignment3\obj\Debug\net6.0\Assignment2.AssemblyInfo.puml
!include .\\CS264\Assignment3\obj\Debug\net6.0\Assignment2.GlobalUsings.g.puml
!include .\\CS264\Assignment3\obj\Debug\net6.0\Assignment3.AssemblyInfo.puml
!include .\\CS264\Assignment3\obj\Debug\net6.0\Assignment3.GlobalUsings.g.puml
!include .\\CS264\Assignment4\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\CS264\Assignment4\obj\Debug\net6.0\Assignment4.AssemblyInfo.puml
!include .\\CS264\Assignment4\obj\Debug\net6.0\Assignment4.GlobalUsings.g.puml
!include .\\CS264\Assignment5\Assignment5_2\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\CS264\Assignment5\Assignment5_2\obj\Debug\net6.0\Assignment2.AssemblyInfo.puml
!include .\\CS264\Assignment5\Assignment5_2\obj\Debug\net6.0\Assignment2.GlobalUsings.g.puml
!include .\\CS264\Assignment5\Assignment5_3\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\CS264\Assignment5\Assignment5_3\obj\Debug\net6.0\Assignment2.AssemblyInfo.puml
!include .\\CS264\Assignment5\Assignment5_3\obj\Debug\net6.0\Assignment2.GlobalUsings.g.puml
!include .\\CS264\Assignment5\Assignment5_3\obj\Debug\net6.0\Assignment3.AssemblyInfo.puml
!include .\\CS264\Assignment5\Assignment5_3\obj\Debug\net6.0\Assignment3.GlobalUsings.g.puml
!include .\\CS264\Assignment5\Assignment5_4\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\CS264\Assignment5\Assignment5_4\obj\Debug\net6.0\Assignment5.AssemblyInfo.puml
!include .\\CS264\Assignment5\Assignment5_4\obj\Debug\net6.0\Assignment5.GlobalUsings.g.puml
!include .\\CS264\Coding Assignment\Command\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\CS264\Coding Assignment\Command\obj\Debug\net6.0\Assignment1.AssemblyInfo.puml
!include .\\CS264\Coding Assignment\Command\obj\Debug\net6.0\Assignment1.GlobalUsings.g.puml
!include .\\CS264\Coding Assignment\Command\obj\Debug\net6.0\Assignment4.AssemblyInfo.puml
!include .\\CS264\Coding Assignment\Command\obj\Debug\net6.0\Assignment4.GlobalUsings.g.puml
!include .\\CS264\Coding Assignment\Memento\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\CS264\Coding Assignment\Memento\obj\Debug\net6.0\Assignment1.AssemblyInfo.puml
!include .\\CS264\Coding Assignment\Memento\obj\Debug\net6.0\Assignment1.GlobalUsings.g.puml
!include .\\CS264\Coding Assignment\Memento\obj\Debug\net6.0\Assignment2.AssemblyInfo.puml
!include .\\CS264\Coding Assignment\Memento\obj\Debug\net6.0\Assignment2.GlobalUsings.g.puml
!include .\\CS264\Coding Assignment\Memento\obj\Debug\net6.0\Assignment3.AssemblyInfo.puml
!include .\\CS264\Coding Assignment\Memento\obj\Debug\net6.0\Assignment3.GlobalUsings.g.puml
@enduml
