@startuml
class Ellipse {
    + rx : int
    + ry : int
    + cx : int
    + cy : int
    + fill : string
    + stroke : string
    + strokeWidth : string
    + Ellipse(rx:int, ry:int, cx:int, cy:int, fill:string, stroke:string, strokeWidth:string)
    + printShape() : string
}
@enduml
